### ISSUE TITLE
Restructure output to be more sensible

### ISSUE THREAD

**Issue by d3ming** [paperg/tagcompare#14]
Right now there are compare and capture jobs and the output scheme for them are different.  Restructure output so it's:

```
output:
- job id
  - compare: compare output
  - capture: capture output
```
